// Ex 1:Init (after 2) Initialize an array named movies containing the titles of some of your favorite movies
// {
//     let movie = ["game of thrones, the walking dead, godfarther"];
// }

// Ex 2:Create (after 4) Add new item named newMovie into the end of the movies array you initialized, newMovie entered by users
/*{
        let newMovie = prompt("Nhập tên phim bạn muốn add vào list film?");
        let movie = ["game of thrones, the walking dead, godfarther"];
            movie.push(newMovie);
        alert(movie);
}*/

// Ex 3:Read (after 5) Read the item at position i in the movies array, i entered by users
/*{
    let i = prompt(" nhập số tên film bạn muốn xem (1-6)?")
    let movie = ["game of thrones", "the walking dead", "godfarther", "bố già", "gái già lắm chiêu","naruto"];
    alert(movie[i-1]);
}*/

// Ex 4:Update the first item of the movies array into movieTitle, movieTitle entered by users
/*{
    let movie = ["game of thrones", "the walking dead", "godfarther", "bố già", "gái già lắm chiêu","naruto"];
}*/


